### ISSUE TITLE
cmake fails to find io2d package

### ISSUE THREAD

**Issue by aoozdemir** [udacity/CppND-Route-Planning-Project#1]
**OS:** MacOS Mojave 10.14.4
**CMake Version:** 3.14.3
**GNU Make:** 3.81

---

See the full log: https://gist.github.com/aoozdemir/f770ec818bb9dc446722cd05f005b9ea

Error log after running `cmake ..`:
```
➜  io2d git:(master) ✗ cmake .
TESTING = notest
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:27 (find_package):
  By not providing "Findio2d.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "io2d", but
  CMake did not find one.

  Could not find a package configuration file provided by "io2d" with any of
  the following names:

    io2dConfig.cmake
    io2d-config.cmake

  Add the installation prefix of "io2d" to CMAKE_PREFIX_PATH or set
  "io2d_DIR" to a directory containing one of the above files.  If "io2d"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/Users/oz/Desktop/workspace/cpp/io2d/CMakeFiles/CMakeOutput.log".
```

**Comment by aoozdemir** [comment]
An update, if anyone seed this. Issue resolved by following the steps here, https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md

Make sure to do this first, https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md#xcode-and-libc

A small trick is to edit the CMakeLists.txt under P0267_RefImpl and comment out the part with samples. Then, using `CoreGraphics/Mac on macOS` run "ALL_Build" and "install" in XCode.

Thanks to Benjamin H. in our classroom for the detail explanation.

**Comment by karlTUM** [comment]
@aoozdemir Hi I also meet such problem in Ubuntu. After I built the P0267_RefImpl, what else should I do to let io2d be found? Should I change something in the CMAKE file of CppND-Route-Planning-Project?

**Comment by aoozdemir** [comment]
@karlTUM hi! I didn't change anything in the CMAKE of this project. But, perhaps after this build, https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md#cairoxlib-on-linux, you can try to run `make` in the folder where cmake built the io2d.

I'm not sure how to install on ubuntu I'm afraid.

**Comment by karlTUM** [comment]
@aoozdemir  Thank you. I installed P0267_RefImpl as root and it worked. But I have come across anoterh problem:


```
CMake Error at test/CMakeLists.txt:25 (add_executable):
  add_executable called with incorrect number of arguments


CMake Error at test/CMakeLists.txt:28 (target_link_libraries):
  Cannot specify link libraries for target "test" which is not built by this
  project.


-- Configuring incomplete, errors occurred!
See also "/home/kang/Documents/cpp/cpp_eng/CppND-Route-Planning-Project/build/CMakeFiles/CMakeOutput.log".
```

Did you have this problem?

**Comment by aoozdemir** [comment]
@karlTUM nice. I didn't get this error, no. Perhaps, ask in the classroom too. It's possible someone already came across to this.

**Comment by chocolateHszd** [comment]
I'm trying to follow the instructions what's the next step after opening io2d.xcodeproj? my Xcode throws error on this library "cstddef"

**Comment by Horki** [comment]
Any solution for arch linux, besides VM

**Comment by lakshman64** [comment]
Available. Contact me. LAKSHMANZEN@YAHOO.COM 

Sent from Yahoo Mail on Android 
 
  On Tue, Jul 16, 2019 at 5:10 PM, Ivan Zvonimir Horvat<notifications@github.com> wrote:   
Any solution for arch linux, besides VM

**Comment by bander-saeed94** [comment]
This issue should not be closed. I am trying to setup with an ubuntu container after trying with my mac.
The short solution to upload a Docker image for the project. I am trying but this whole week with no success.

**Comment by pbdevpros** [comment]
I agree. I am having the same issues, after trying to build the project. There's little documentation listed with the CppND-Route-Planning-Project on how to build the project. 

I managed to get around the io2d cmake build problem by following the above instructions and then using a load of hacky workarounds, but now I cannot run make as the io2d headers can't be found. It would be helpful to have more guidance here.

**Comment by bander-saeed94** [comment]
@aoozdemir 
Please open the issue since it is not yet resolved.

**Comment by suljaxm** [comment]
install [IO2D](https://github.com/suljaxm/CppND-Route-Planning-Project)
```
sudo apt update
sudo apt install build-essential
sudo apt install cmake
sudo apt install libcairo2-dev
sudo apt install libgraphicsmagick1-dev
sudo apt install libpng-dev

git clone --recurse-submodules https://github.com/cpp-io2d/P0267_RefImpl
cd P0267_RefImpl
mkdir Debug
cd Debug
cmake --config Debug "-DCMAKE_BUILD_TYPE=Debug" ..
cmake --build .
sudo make install
```

**Comment by baoqger** [comment]
I am using windows system. If a docker image for this project is provided, it will be  great.

**Comment by baoqger** [comment]
> @aoozdemir Hi I also meet such problem in Ubuntu. After I built the P0267_RefImpl, what else should I do to let io2d be found? Should I change something in the CMAKE file of CppND-Route-Planning-Project?

I used a ubuntu docker image, but fail to build. Can you share more information? Or just follow the doc working for you.

**Comment by baoqger** [comment]
> An update, if anyone sees this. Issue resolved by following the steps here, https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md
> 
> Make sure to do this first, https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md#xcode-and-libc
> 
> A small trick is to edit the CMakeLists.txt under P0267_RefImpl and comment out the part with samples. Then, using `CoreGraphics/Mac on macOS` run "ALL_Build" and "install" in XCode.
> 
> Thanks to Benjamin H. in our classroom for the detail explanation.

"comment out the part with samples", this means what? Can you give more details. Thank you

**Comment by aoozdemir** [comment]
> > An update, if anyone sees this. Issue resolved by following the steps here, https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md
> > Make sure to do this first, https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md#xcode-and-libc
> > A small trick is to edit the CMakeLists.txt under P0267_RefImpl and comment out the part with samples. Then, using `CoreGraphics/Mac on macOS` run "ALL_Build" and "install" in XCode.
> > Thanks to Benjamin H. in our classroom for the detail explanation.
> 
> "comment out the part with samples", this means what? Can you give more details. Thank you

If I recall correctly, I meant this.
https://github.com/cpp-io2d/P0267_RefImpl/blob/master/CMakeLists.txt#L38-L40

**Comment by Nyrathalnian** [comment]
Does anyone have a workaround for windows I am also getting the errors where IO2D is missing header files and cannot be found within the project?

**Comment by z1yuan** [comment]
I just met the exactly the same error on my ubuntu. 

>   Could not find a package configuration file provided by "io2d" with any of
  the following names:

    io2dConfig.cmake
    io2d-config.cmake

and after some experiments i find out that it is because the CMake find_package will not be able to find "io2d". So just we need to **git clone your io2d into /opt/c++** for example, and follow the install instruction. After this everything goes well in my case.

**Comment by Shivam-Bhardwaj** [comment]
After 
`cmake --build .` during installation of IO2D
add
`sudo make install`

this will copy the necessary files at places where Cmake can find them.

**Comment by AbdSam94** [comment]
how can i install on windows after the cmake .. command i'm having a hard time building CppND-Route-Planning-Project as it can't find the IO2dconfig.cmake files

**Comment by UTDEngineer** [comment]
> After
> `cmake --build .` during installation of IO2D
> add
> `sudo make install`
> 
> this will copy the necessary files at places where Cmake can find them.

This is a solution for Ubuntu Linux. I have successfully tried it.

**Comment by AbdSam94** [comment]
unfortunately I'm working on wndiows

**Comment by UTDEngineer** [comment]
> unfortunately I'm working on wndiows

Why use windows such a broken OS, come to use Linux :)

**Comment by AbdSam94** [comment]
> > unfortunately I'm working on wndiows
> 
> Why use windows such a broken OS, come to use Linux :)

I will eventually ;)

**Comment by toaderandrei** [comment]
> > > An update, if anyone sees this. Issue resolved by following the steps here, https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md
> > > Make sure to do this first, https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md#xcode-and-libc
> > > A small trick is to edit the CMakeLists.txt under P0267_RefImpl and comment out the part with samples. Then, using `CoreGraphics/Mac on macOS` run "ALL_Build" and "install" in XCode.
> > > Thanks to Benjamin H. in our classroom for the detail explanation.
> > 
> > 
> > "comment out the part with samples", this means what? Can you give more details. Thank you
> 
> If I recall correctly, I meant this.
> `under P0267_RefImpl comment out the part with samples`
> https://github.com/cpp-io2d/P0267_RefImpl/blob/master/CMakeLists.txt#L38-L40

For one that does not have enough exp with building in c++ it is not easy. I think a bit more help and documentation is required.

**Comment by vaddipar** [comment]
Hello Anyone from the future: Here is a detailed wiki for fixing the same:
https://t.co/CljjTK2aws?amp=1

**Comment by Horki** [comment]
> Hello Anyone from the future: Here is a detailed wiki for fixing the same:
> https://t.co/CljjTK2aws?amp=1

Nice post, you could also install **GTest** and **pugiXML** via [Conan](https://conan.io/) 
Also you could see my (solution)[https://github.com/Horki/CppND-Route-Planning-Project]

**Comment by vaddipar** [comment]
@Horki  thanks for introducing Conan to me. I did not hear of it till now. Will surely take a look.

**Comment by harrisrobin** [comment]
I still run into this and have not managed to get past it. None of the workarounds here work.

I'm on macOS Catalina (version 10.15.4).

**Comment by baoqger** [comment]
> install [IO2D](https://github.com/suljaxm/CppND-Route-Planning-Project)
> 
> ```
> sudo apt update
> sudo apt install build-essential
> sudo apt install cmake
> sudo apt install libcairo2-dev
> sudo apt install libgraphicsmagick1-dev
> sudo apt install libpng-dev
> 
> git clone --recurse-submodules https://github.com/cpp-io2d/P0267_RefImpl
> cd P0267_RefImpl
> mkdir Debug
> cd Debug
> cmake --config Debug "-DCMAKE_BUILD_TYPE=Debug" ..
> cmake --build .
> sudo make install
> ```

"sudo make install" can install the io2d into the system, right? Then cmake of main project can find it.

**Comment by baoqger** [comment]
> Hello Anyone from the future: Here is a detailed wiki for fixing the same:
> https://t.co/CljjTK2aws?amp=1

I also read this post. But I don't understand how it can allow cmake find the io2d package. can you add more explanation? After I build the io2d library. how to do that? In this post, it just mentioned "10. Open the io2d.xcodeproj file in XCode and run the same." how it works?

**Comment by vaddipar** [comment]
@baoqger  where have you placed the io2d builds? cmake is able to find the io2d project for me fine.

**Comment by aoozdemir** [comment]
I'm closing this issue, as it'll probably never close and has become a source of distracting notifications that could be discussed in the Udacity classroom with your mentors or your classmates.

The solutions that are already posted here will most likely solve your problem. You may continue to have the conversation here, I'm just tired of this issue being raised from inactivity every now and then.

All the best.

**Comment by harrisrobin** [comment]
@aoozdemir I know this is closed, but just to avoid more people getting confused the solutions posted here do not solve the issue for Mac users. Udacity mentors have acknowledged this and from what I understood are working on a fix to the instructions.

**Comment by mylescallan** [comment]
I am using a mac and got it up and running locally yesterday.

[I documented the steps here](https://github.com/mylescallan/OpenStreetMaps_C-) if that is any use to anyone.

Next step, get it up and running in Xcode so that I can see what the OSM data looks like when loaded. Wish me luck!

**Comment by hemulens** [comment]
> I just met the exactly the same error on my ubuntu.
> 
> > Could not find a package configuration file provided by "io2d" with any of
> > the following names:
> 
> ```
> io2dConfig.cmake
> io2d-config.cmake
> ```
> 
> and after some experiments i find out that it is because the CMake find_package will not be able to find "io2d". So just we need to **git clone io2d into /opt/c++** for example, and follow the [install](https://github.com/udacity/CppND-Route-Planning-Project/issues/1#issuecomment-520659977) instruction. After this everything goes well in my case.

Hello! Could you please explain where you found "**/opt/c++**"?

**Comment by Toulik-Das** [comment]
CMake script expects cairo and graphicsmagick to be installed. libpng is required in order to run tests. These installation steps assume APT package manager on Ubuntu Linux. Installation steps:

Refresh apt: sudo apt update
Install GCC: sudo apt install build-essential
Install CMake: sudo apt install cmake
Install Cairo: sudo apt install libcairo2-dev
Install graphicsmagick: sudo apt install libgraphicsmagick1-dev
Install libpng: sudo apt install libpng-dev
Example of CMake execution:

git clone --recurse-submodules https://github.com/cpp-io2d/P0267_RefImpl
cd P0267_RefImpl
mkdir Debug
cd Debug
cmake --config Debug "-DCMAKE_BUILD_TYPE=Debug" ..
cmake --build .

**Comment by ridwan102** [comment]
> I am using a mac and got it up and running locally yesterday.
> 
> [I documented the steps here](https://github.com/mylescallan/OpenStreetMaps_C-) if that is any use to anyone.
> 
> Next step, get it up and running in Xcode so that I can see what the OSM data looks like when loaded. Wish me luck!

Thanks so much! This worked like a charm. The instructions were exceptional with visuals

**Comment by Ishaanyp** [comment]
> cmake --build .

Hi thanks for your comment, it worked until i run above command @suljaxm. 

But above command didn't work. It threw following error: 

> /Users/ishan/Documents/github/cpp/CppND-Route-Planning-Project/thirdparty/P0267_RefImpl/P0267_RefImpl/P0267_RefImpl/xio2d.h:4:10:

> fatal error: 
      'limits' file not found
#include <limits>
         ^~~~~~~~
1 error generated.

Any idea how that header seems to be missing? Thanks.

**Comment by nishinkvasu** [comment]
Anyone got it to work on windows?

**Comment by jesselee34** [comment]
Also trying to get it working on windows.

**Comment by nishinkvasu** [comment]
> Also trying to get it working on windows.

I kind of got it running in windows.. vcpkg can install io2d, it compiles the other libraries as x86 and then used CMAKE_PREFIX_TOOLCHAIN to point to the vcpkg cmake script.. it created a MSVC project.. but I think that is not what they expect... was not able to build io2d myself such that CMake finds it

**Comment by jesselee34** [comment]
So I tried this approach but when I run cmake it dies at the io2dConfig.cmake saying " Could not find a package configuration file provided by "unofficial-cairo"

Did you run into this?

**Comment by nishinkvasu** [comment]
Sorry for the late reply.. I think I did face something similar.. not sure when though.. the cmake goes thru with the following command.. - 

cmake -DCMAKE_TOOLCHAIN_FILE=pathtovcpkg.cmake ..

**Comment by azzamshaikh** [comment]
hello @jesselee34, @nishinkvasu 

I am having issues with the 'could not find package' on windows as well. i haven't really found a solution. Any luck on this?

**Comment by nishinkvasu** [comment]
Hi @azzamshaikh ,

I installed the io2d through the vcpkg and used the following command so that it is identified by cmake.
cmake -DCMAKE_TOOLCHAIN_FILE=path to buildsystems\vcpkg.cmake ..

Was able to create a MSVC project this way.

**Comment by Banacial** [comment]
So what now about solving this on Windows ? 
I don't know at all what i should do now, as of now i do not even know whether this magical io2d thing is P0267_Reflmpl by any chance. I went through the installation guidline outlined in BUILDING.md but cannot make sense of the General Notes (just followed the Cairo/win32 ) and am now stuck on the ususal:

 Could not find a package configuration file provided by "io2d" with any of
  the following names:

    io2dConfig.cmake
    io2d-config.cmake 
error. Additionally i dont know how to make sense of this instruction:

I kind of got it running in windows.. vcpkg can install io2d, it compiles the other libraries as x86 and then used CMAKE_PREFIX_TOOLCHAIN to point to the vcpkg cmake script.. it created a MSVC project.. but I think that is not what they expect... was not able to build io2d myself such that CMake finds it

or this:

I installed the io2d through the vcpkg and used the following command so that it is identified by cmake.
cmake -DCMAKE_TOOLCHAIN_FILE=path to buildsystems\vcpkg.cmake ..

since doesn't seem to exist.

**Comment by PavanproJack** [comment]
> I am using a mac and got it up and running locally yesterday.
> 
> [I documented the steps here](https://github.com/mylescallan/OpenStreetMaps_C-) if that is any use to anyone.
> 
> Next step, get it up and running in Xcode so that I can see what the OSM data looks like when loaded. Wish me luck!

Many Thanks. This helped a lot saving my time. Perfect documentation in fact.

**Comment by SchneiderJs** [comment]
> After
> `cmake --build .` during installation of IO2D
> add
> `sudo make install`
> 
> this will copy the necessary files at places where Cmake can find them.

Thanks, that worked for me!

**Comment by charity1475** [comment]
When i reach this step i get an error.
cmake --build .

                from /home/charity/UAD/P0267_RefImpl/P0267_RefImpl/Samples/svg/svg.cpp:5:
/home/charity/UAD/P0267_RefImpl/P0267_RefImpl/Samples/svg/external/svgpp/include/svgpp/policy/value_events.hpp:23:5: note:   candidate expects 2 arguments, 3 provided
   23 |     context.set(tag, args...);
      |     ^~~~~~~
make[2]: *** [P0267_RefImpl/Samples/svg/CMakeFiles/svg.dir/build.make:76: P0267_RefImpl/Samples/svg/CMakeFiles/svg.dir/svg.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:677: P0267_RefImpl/Samples/svg/CMakeFiles/svg.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by yyccphus** [comment]
> install [IO2D](https://github.com/suljaxm/CppND-Route-Planning-Project)
> 
> ```
> sudo apt update
> sudo apt install build-essential
> sudo apt install cmake
> sudo apt install libcairo2-dev
> sudo apt install libgraphicsmagick1-dev
> sudo apt install libpng-dev
> 
> git clone --recurse-submodules https://github.com/cpp-io2d/P0267_RefImpl
> cd P0267_RefImpl
> mkdir Debug
> cd Debug
> cmake --config Debug "-DCMAKE_BUILD_TYPE=Debug" ..
> cmake --build .
> sudo make install
> ```

"cmake --config Debug "-DCMAKE_BUILD_TYPE=Debug" .. " seems doesn't work, since it tells me "CMake Error: Unknown argument --config"

**Comment by charity1475** [comment]
I changed something and it worked for me
cmake --config Debug "-DCMAKE_BUILD_TYPE=Debug" ..
cmake ..
make
sudo make install

**Comment by yyccphus** [comment]
> I changed something and it worked for me
> cmake --config Debug "-DCMAKE_BUILD_TYPE=Debug" ..
> cmake ..
> make
> sudo make install

Thanks, it worked for me, too.

**Comment by TimG1997** [comment]
> install [IO2D](https://github.com/suljaxm/CppND-Route-Planning-Project)
> 
> ```
> sudo apt update
> sudo apt install build-essential
> sudo apt install cmake
> sudo apt install libcairo2-dev
> sudo apt install libgraphicsmagick1-dev
> sudo apt install libpng-dev
> 
> git clone --recurse-submodules https://github.com/cpp-io2d/P0267_RefImpl
> cd P0267_RefImpl
> mkdir Debug
> cd Debug
> cmake --config Debug "-DCMAKE_BUILD_TYPE=Debug" ..
> cmake --build .
> sudo make install
> ```

I managed to get it working under windows with the following steps:
- enable WSL (Windows Subsystem for Linux) and use f.e. a distribution like Ubuntu (available from the windows store): https://ubuntu.com/wsl
- Install the required dependencies (compiler, cmake etc.) in the WSL (f.e. Ubuntu) according to the answer of @suljaxm 
- configure CLion to use the WSL toolchain: https://www.jetbrains.com/help/clion/how-to-use-wsl-development-environment-in-product.html#wsl-tooclhain
- use the WSL toolchain to build the project

**Comment by aaronespasa** [comment]
I have followed the steps of this tutorial: [Readme for the installation of IO2d in MacOS](https://github.com/mylescallan/OpenStreetMaps_C-)

At the time of running the command `./OSM_A_star_search`, I get the following error:
`Assertion failed: (back_buffer_size.width >= 1. && back_buffer_size.height >= 1. && display_buffer_size.width >= 1. && display_buffer_size.height >= 1.), function _ScaledBackBufferRect, file /Users/aaron/Documents/github/CppND-Route-Planning-Project/thirdparty/P0267_RefImpl/P0267_RefImpl/P0267_RefImpl/coregraphics/xio2d_cg_display.cpp, line 9.`

The line 9 of that file is:
`assert(back_buffer_size.width >= 1. && back_buffer_size.height >= 1. &&
           display_buffer_size.width >= 1. && display_buffer_size.height >= 1. );`

If I comment those lines, IO2D executes a blank window:
<img width="434" alt="Screenshot 2021-05-27 at 12 25 32" src="https://user-images.githubusercontent.com/39239895/119810768-a54d6380-bee6-11eb-9fb9-d0640b9a6a57.png">

I'm currently using macOS Big Sur with the chip M1.

**Comment by tensory** [comment]
Using cmake 3.2.1, the `--config` flag was removed (from cmake 3.2.0). I have not been able to find instructions for an alternate way to provide that flag. The io2D README has not been updated for cmake 3.2.0. Naturally, `cmake --help` provides no clear alternative.

If I try to run cmake with `cmake --build .` instead of providing a `--config` flag, I get this error 
```
P0267_RefImpl/P0267_RefImpl/P0267_RefImpl/cairo/xlib/xio2d_cairo_xlib_output_surfaces.h:4:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
```

I tried defining `CPPFLAGS="-nostdinc++ -isystem/Users/ari.lacenski/Development/cppnano/CppND-Route-Planning-Project/dependencies/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1 -I/usr/local/include/X11"

and I also tried to provide a valid path to the X11 directory in my Xcode-12.4app/ dir
but neither the path at /usr/local/include nor the Xcode-included X11 resolved the "'X11/Xlib.h' file not found" error.

**Comment by tensory** [comment]
I got IO2D installed on OSX using Xcode and MacPorts. I'm going to leave my environment variables here. Hope it helps someone.

Details:
1. The variable is called CXXFLAGS, not CPPFLAGS
2.  The `-nostdinc++` flag is from [this part](https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md#xcode-and-libc) of the IO2D Readme.
3. The `-I/Applications/Xcode-12.4.app/...` flag resolves a problem where Cmake cannot find X11 headers: `'X11/Xlib.h' file not found` If you aren't getting that error (lucky you) you might not need this flag. Note the `-I` (capital letter "i", not "ell") before the path. That Xcode path is specific to my machine; your path will be different. I got the idea [from this GitHub issue](https://github.com/pinax/pinax-project-teams/issues/1).
4. The `-isystem/opt/X11/include` and related flags are from [IO2D Readme](https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md#cairoxlib-on-macos). See where they concatenated the flags to a prior $CXXFLAGS? I chose to put it all in one `CXXFLAGS` value.
5. Don't forget to also define `$LDFLAGS` 🥰
```
~/Development/cppnano/P0267_RefImpl/Debug % echo $CXXFLAGS
-nostdinc++ -isystem/Users/ari.lacenski/Development/cppnano/RoutePlanningProject-Dependencies/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1 -I/Applications/Xcode-12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/X11 -isystem/opt/X11/include -isystem/opt/local/include -isystem/usr/local/include

~/Development/cppnano/P0267_RefImpl/Debug % echo $LDFLAGS
-L/Users/ari.lacenski/Development/cppnano/RoutePlanningProject-Dependencies/clang+llvm-6.0.0-x86_64-apple-darwin/lib -Wl,-rpath,/Users/ari.lacenski/Development/cppnano/RoutePlanningProject-Dependencies/clang+llvm-6.0.0-x86_64-apple-darwin/lib
```

**Comment by bhavikkasundra55** [comment]
> install [IO2D](https://github.com/suljaxm/CppND-Route-Planning-Project)
> 
> ```
> sudo apt update
> sudo apt install build-essential
> sudo apt install cmake
> sudo apt install libcairo2-dev
> sudo apt install libgraphicsmagick1-dev
> sudo apt install libpng-dev
> 
> git clone --recurse-submodules https://github.com/cpp-io2d/P0267_RefImpl
> cd P0267_RefImpl
> mkdir Debug
> cd Debug
> cmake --config Debug "-DCMAKE_BUILD_TYPE=Debug" ..
> cmake --build .
In which directory to clone ?

**Comment by Rank-N-Tensor** [comment]
> When i reach this step i get an error.
> cmake --build .
> 
> ```
>             from /home/charity/UAD/P0267_RefImpl/P0267_RefImpl/Samples/svg/svg.cpp:5:
> ```
> 
> /home/charity/UAD/P0267_RefImpl/P0267_RefImpl/Samples/svg/external/svgpp/include/svgpp/policy/value_events.hpp:23:5: note: candidate expects 2 arguments, 3 provided
> 23 | context.set(tag, args...);
> | ^~~~~~~
> make[2]: *** [P0267_RefImpl/Samples/svg/CMakeFiles/svg.dir/build.make:76: P0267_RefImpl/Samples/svg/CMakeFiles/svg.dir/svg.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:677: P0267_RefImpl/Samples/svg/CMakeFiles/svg.dir/all] Error 2
> make: *** [Makefile:141: all] Error 2

**Comment by Rank-N-Tensor** [comment]
@bhavikkasundra55 did you install it in the cloned route planner folder or separately?

**Comment by Rank-N-Tensor** [comment]
> I changed something and it worked for me
> cmake --config Debug "-DCMAKE_BUILD_TYPE=Debug" ..
> cmake ..
> make
> sudo make install

@charity1475 , i tried this , make throws the same error again? do you have a workaround? also, did you install this in the route planner folder or separately?

**Comment by bhavikkasundra55** [comment]
> @bhavikkasundra55 did you install it in the cloned route planner folder or separately? 

I did it separately, 
Did i have to clone io2D repository in cpp-route-planner directory?

**Comment by Rank-N-Tensor** [comment]
No , you didn't. The issue on linux has to do with the version of the svgpp submodule. Check issue #136 for more information.

**Comment by Seim2k17** [comment]
> something and

Hey what exactly did you change ?

**Comment by Seim2k17** [comment]
i redid the whole process and it worked for me with the following steps:

# 1. removed the whole local copy of the repository
` sudo rm -fr P0267_RefImpl/ `

#2. clone the repo again
`git clone --recurse-submodules https://github.com/cpp-io2d/P0267_RefImpl ` 

#3. make debug dir
`mkdir Debug`

#4. goto dir
`cd Debug`

#5. i have  cmake 3.2x and the --config option is no more available so i only did
`cmake ..`

#6 the build
`cmake --build .`

**Comment by Seim2k17** [comment]
what confuses me and i didn't looked at it exactly - there are two repositories!
1. the io2d library
2. the routerplannerproject
So after doing the stuff from my last command one still need to compile the project and then we have an executable.
also see here carefully: https://gist.github.com/wAuner/68ee426b87d297340826660f5ac62b79

**Comment by lederle** [comment]
> No , you didn't. The issue on linux has to do with the version of the svgpp submodule. Check issue #136 for more information.

I can confirm this, on Ubuntu 20.04 I had to update svgpp to the 1.3.0 tag in the svgpp submodule to get io2d to build. Issue [#136](https://github.com/cpp-io2d/P0267_RefImpl/issues/136) refers to the io2d issue where this was raised.

For some reason the `HEAD` in the svgpp submodule is detached at commit `a33934a`, which is prior to the v1.3.0 fix. Once you checkout the fix, io2d will build (assuming you were stuck on the svgpp issue).

Do:
`cd P0267_RefImpl/P0267_RefImpl/Samples/svg/external/svgpp`
`git checkout tags/v1.3.0`

You can `git checkout master` as well, it is a few commits ahead of `v1.3.0`.

**Comment by Aadi775** [comment]
Whenever i reach 66% in `cmake ..` i get these errors`/home/aadi/P0267_RefImpl/P0267_RefImpl/Samples/svg/svg.cpp:231:10: note:   candidate expects 2 arguments, 3 provided
make[2]: *** [P0267_RefImpl/Samples/svg/CMakeFiles/svg.dir/build.make:90: P0267_RefImpl/Samples/svg/CMakeFiles/svg.dir/svg.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:631: P0267_RefImpl/Samples/svg/CMakeFiles/svg.dir/all] Error 2
make: *** [Makefile:146: all] Error 2`

**Comment by jonna-t1** [comment]
Where do you clone io2d or does it not matter? 
"clone --recurse-submodules https://github.com/cpp-io2d/P0267_RefImpl"

**Comment by stevendae** [comment]
Commenting out Line 38 to 30 in the CMakeLists.txt file gets rid of the errors in installing the sample and lets you proceed with the rest of the build.

This is on Ubuntu 20.04.

**Comment by Shyam-NR** [comment]
> Where do you clone io2d or does it not matter? "clone --recurse-submodules https://github.com/cpp-io2d/P0267_RefImpl"

Yeah it does matter and clone it into the third-party folder

**Comment by PatrickGono** [comment]
I managed to finally get it running on windows.

1) Install vcpkg and the required packaged as per the instructions [here](https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md#cairowin32-on-windows)
2) To install io2d, follow the rest of the instructions, but instead of the listed command:
`cmake -G "Visual Studio 15 2017 Win64" --config Debug "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" ../.`
you should run:
`cmake.exe -G "Visual Studio 17 2022" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_TOOLCHAIN_FILE=C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DCHARSET_LIB=C:\tools\vcpkg\installed\x64-windows\debug\lib\charset.lib" "-DEXPAT_LIB=C:\tools\vcpkg\packages\expat_x64-windows\debug\lib\libexpat.lib" "-DICONV_LIB=C:\tools\vcpkg\installed\x64-windows\debug\lib\iconv.lib" ../.` (i.e. remove `--config Debug` and manually set paths to the relevant packages).
3) This should create a `io2d.sln` file in the current folder. Open it with Visual Studio _with admin privileges_ (if your `Program Files (x86)` folder is protected), and select **Build**->**Build solution**
4) Once built, rightlick on the INSTALL project in the solution explorer (in the side panel, usually), and click **Build**.
5) You should now have an `io2d` folder in your `Program Files (x86)`.
6) Go to the `CppND-Route-Planning-Project` folder, create a `Build` folder, enter it.
7) Run
`cmake ../. -DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DPKG_CONFIG_EXECUTABLE=C:/tools/vcpkg/packages/pkgconf_x64-windows/tools/pkgconf/pkgconf.exe -DCAIRO_LIBRARIES=C:/tools/vcpkg/installed/x64-windows/lib -DGRAPHICSMAGICK_LIBRARIES=C:/tools/vcpkg/installed/x64-windows/lib -DCAIRO_INCLUDE_DIRS=C:/tools/vcpkg/installed/x64-windows/include/cairo -DGRAPHICSMAGICK_INCLUDE_DIRS=C:/tools/vcpkg/installed/x64-windows/include/magick`
8) Open the built `OSM_A_star_search.sln` file in Visual Studio. When you build this project, it should fail with code-relevant errors, such as functions not returning the specified value
9) For me it didn't (still missing some path to a lib), so I gave up, and decided to finish this one in the web workspace udacity provides

**Comment by akshaypatel774** [comment]
> I am using windows system. If a docker image for this project is provided, it will be great.

Did you get it working in windows or not?

**Comment by felixhoernle** [comment]
> I have followed the steps of this tutorial: [Readme for the installation of IO2d in MacOS](https://github.com/mylescallan/OpenStreetMaps_C-)
> 
> At the time of running the command `./OSM_A_star_search`, I get the following error: `Assertion failed: (back_buffer_size.width >= 1. && back_buffer_size.height >= 1. && display_buffer_size.width >= 1. && display_buffer_size.height >= 1.), function _ScaledBackBufferRect, file /Users/aaron/Documents/github/CppND-Route-Planning-Project/thirdparty/P0267_RefImpl/P0267_RefImpl/P0267_RefImpl/coregraphics/xio2d_cg_display.cpp, line 9.`
> 
> The line 9 of that file is: `assert(back_buffer_size.width >= 1. && back_buffer_size.height >= 1. && display_buffer_size.width >= 1. && display_buffer_size.height >= 1. );`
> 
> And the problem is that both display_buffer_size.width and display_buffer_size.height are 1.
> 
> If I comment those lines, IO2D executes a blank window: <img alt="Screenshot 2021-05-27 at 12 25 32" width="434" src="https://user-images.githubusercontent.com/39239895/119810768-a54d6380-bee6-11eb-9fb9-d0640b9a6a57.png">
> 
> I'm currently using macOS Big Sur with the chip M1.

I have the same issue using macOS Sonoma with M2 chip and not been able to solve it so far.
