### ISSUE TITLE
cannot make the io2d 

### ISSUE THREAD

**Issue by zhuangxiaopi** [udacity/CppND-Route-Planning-Project#11]
I follow the readme to install io2d,but i encouter .
here is my clang+llvm...'s location
1.`export LDFLAGS="-L/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/lib -Wl,-rpath,/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/lib"`

2.`export CXXFLAGS="-nostdinc++ -isystem/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1"
`

-- The CXX compiler identification is GNU 8.2.0
-- Check for working CXX compiler: /usr/local/bin/c++
-- Check for working CXX compiler: /usr/local/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Default IO2D backend was not specified, choosing automatically...
Found Linux, using CAIRO_XLIB.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found Cairo: /usr/include/cairo (found version "1.14.6") 
-- Checking for module 'GraphicsMagick'
--   Found GraphicsMagick, version 1.3.23
-- Found GraphicsMagick: /usr/include/GraphicsMagick  
-- The C compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
Skipping the Maps example since Boost was not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhuang/P0267_RefImpl/Debug

And Then `cmake --build . `
Now Now Now I have hundreds of error,as following:
Scanning dependencies of target io2d_core
[  2%] Building CXX object P0267_RefImpl/P0267_RefImpl/CMakeFiles/io2d_core.dir/rgba_color.cpp.o
[  4%] Building CXX object P0267_RefImpl/P0267_RefImpl/CMakeFiles/io2d_core.dir/xinterchangebuffer.cpp.o
[  6%] Linking CXX static library libio2d_core.a
[  6%] Built target io2d_core
Scanning dependencies of target io2d_cairo
[  8%] Building CXX object P0267_RefImpl/P0267_RefImpl/cairo/CMakeFiles/io2d_cairo.dir/cairo_renderer-graphicsmagickinit.cpp.o
[ 10%] Linking CXX static library libio2d_cairo.a
[ 10%] Built target io2d_cairo
Scanning dependencies of target io2d_cairo_xlib
[ 12%] Building CXX object P0267_RefImpl/P0267_RefImpl/cairo/xlib/CMakeFiles/io2d_cairo_xlib.dir/cairo_renderer_xlib.cpp.o
[ 14%] Linking CXX static library libio2d_cairo_xlib.a
[ 14%] Built target io2d_cairo_xlib
Scanning dependencies of target color_fill
[ 17%] Building CXX object P0267_RefImpl/Samples/color_fill/CMakeFiles/color_fill.dir/main.cpp.o
[ 19%] Linking CXX executable color_fill
CMakeFiles/color_fill.dir/main.cpp.o：在函数‘std::bad_optional_access::bad_optional_access()’中：
/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1/optional:167：对‘vtable for std::bad_optional_access’未定义的引用
CMakeFiles/color_fill.dir/main.cpp.o：在函数‘std::experimental::io2d::v1::_Cairo::_Throw_if_failed_cairo_status_t(_cairo_status)’中：
/home/zhuang/P0267_RefImpl/P0267_RefImpl/P0267_RefImpl/cairo/xcairo_helpers.h:17：对‘std::bad_alloc::bad_alloc()’未定义的引用
CMakeFiles/color_fill.dir/main.cpp.o：在函数‘std::__1::__shared_weak_count::__release_shared()’中：
/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1/memory:3533：对‘std::__1::__shared_weak_count::__release_weak()’未定义的引用
/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1/memory:3533：对‘std::__1::__shared_weak_count::__release_weak()’未定义的引用
CMakeFiles/color_fill.dir/main.cpp.o：在函数‘std::__1::__throw_bad_optional_access()’中：
/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1/optional:186：对‘std::bad_optional_access::~bad_optional_access()’未定义的引用
/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1/optional:186：对‘typeinfo for std::bad_optional_access’未定义的引用
/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1/optional:186：对‘std::bad_optional_access::~bad_optional_access()’未定义的引用
/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1/optional:186：对‘typeinfo for std::bad_optional_access’未定义的引用
/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1/optional:186：对‘std::bad_optional_access::~bad_optional_access()’未定义的引用
/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1/optional:186：对‘typeinfo for std::bad_optional_access’未定义的引用
CMakeFiles/color_fill.dir/main.cpp.o：在函数‘std::__1::make_error_code(std::__1::errc)’中：
/home/zhuang/clang+llvm-6.0.0-x86_64-apple-darwin/include/c++/v1/system_error:564：对‘std::__1::generic_category()’未定义的引用
CMakeFiles/color_fill.dir/main.cpp.o：在函数‘std::experimental::io2d::v1::_Cairo::_Cairo_graphics_surfaces<std::experimental::io2d::v1::_Graphics_math_float_impl>::surfaces::create_output_surface(int, int, std::experimental::io2d::v1::format, std::experimental::io2d::v1::scaling, std::experimental::io2d::v1::refresh_style, float)’中：
/home/zhuang/P0267_RefImpl/P0267_RefImpl/P0267_RefImpl/cairo/xlib/xio2d_cairo_xlib_output_surfaces.h:73：对‘std::__1::system_error::system_error(std::__1::error_code)’未定义的引用

Where I make a mis..???

**Comment by z1yuan** [comment]
are you using MAC or linux? In case you are using linux(ubuntu for example), you are then using wrong clang llvm, bause clang+llvm-6.0.0-x86_64-apple-darwin is for MAC, the page https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md#xcode-and-libc is wrong, the download link is for MAC only!

**Comment by SudKul** [comment]
Closing out, as this thread seems inactive.
For user-specific issues, we suggest you refer to the Knowledge hub and reach out to your assigned mentor.
Thanks

**Comment by kishevans** [comment]
@zhuangxiaopi  did you resolve the issue? I have encountered a similar problem
