### ISSUE TITLE
Unable to compile io2d

### ISSUE THREAD

**Issue by metallo25** [udacity/CppND-Route-Planning-Project#12]
I am trying to compile I02D and it has some issues in the cmake. 

`Scanning dependencies of target io2d_core
[  2%] Building CXX object P0267_RefImpl/P0267_RefImpl/CMakeFiles/io2d_core.dir/rgba_color.cpp.o
In file included from /home/karthik/catkin_ws/c++_nanodegree/project_planner/P0267_RefImpl/P0267_RefImpl/P0267_RefImpl/rgba_color.cpp:1:0:
/home/karthik/catkin_ws/c++_nanodegree/project_planner/P0267_RefImpl/P0267_RefImpl/P0267_RefImpl/xio2d.h:18:19: fatal error: variant: No such file or directory
compilation terminated.
P0267_RefImpl/P0267_RefImpl/CMakeFiles/io2d_core.dir/build.make:62: recipe for target 'P0267_RefImpl/P0267_RefImpl/CMakeFiles/io2d_core.dir/rgba_color.cpp.o' failed
make[2]: *** [P0267_RefImpl/P0267_RefImpl/CMakeFiles/io2d_core.dir/rgba_color.cpp.o] Error 1
CMakeFiles/Makefile2:341: recipe for target 'P0267_RefImpl/P0267_RefImpl/CMakeFiles/io2d_core.dir/all' failed
make[1]: *** [P0267_RefImpl/P0267_RefImpl/CMakeFiles/io2d_core.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`

Clearly the xio2d.h is in the corresponding folder, but it is not able to find it still. 
I am on ubuntu 16.04.

**Comment by zamantousif** [comment]
Did you manage to solve this error? If yes, could you update the solution here please.

**Comment by brunoeducsantos** [comment]
I have the same issue

**Comment by brunoeducsantos** [comment]
Sorted it out. You just need to upgrade to gcc 7.0.
https://gist.github.com/jlblancoc/99521194aba975286c80f93e47966dc5

**Comment by Cesaire-Njietche** [comment]
Upgrade cmake >= 8.0 and g++ >=7.0

**Comment by djhanove** [comment]
> Upgrade cmake >= 8.0 and g++ >=7.0

This worked for me!
There are a few things to watch out for. See these links for updating cmake when you have ROS also installed (if you try to get rid of the old cmake version, you'll break the entire ROS distro)

https://answers.ros.org/question/293119/how-can-i-updateremove-cmake-without-partially-deleting-my-ros-distribution/

Finally, update g++ to version 7 following the steps in this link
https://tuxamito.com/wiki/index.php/Installing_newer_GCC_versions_in_Ubuntu

**Comment by mabouseif** [comment]
@djhanove Worked like a charm! Thanks!

**Comment by SudKul** [comment]
Closing out, as this thread seems inactive. 
For user-specific issues, we suggest you refer to the Knowledge hub and reach out to your assigned mentor. 
Thanks

**Comment by MichelML** [comment]
thanks @djhanove
