### ISSUE TITLE
Run test fails

### ISSUE THREAD

**Issue by sharathrjtr** [udacity/CppND-Route-Planning-Project#14]
Running the test executable provides the following failure.
What might be wrong here?
I'm running on Ubuntu 18.04 with cmake version 3.14.7. 
I've io2d installed as in [link](https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md#cairoxlib-on-linux)
```
sj@sj:~/learning/cpp_nanodegree/CppND-Route-Planning-Project/build$ ./test
Running main() from /home/sj/learning/cpp_nanodegree/CppND-Route-Planning-Project/thirdparty/googletest/googletest/src/gtest_main.cc
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from RoutePlannerTest
[ RUN      ] RoutePlannerTest.TestCalculateHValue
/home/sj/learning/cpp_nanodegree/CppND-Route-Planning-Project/test/utest_rp_a_star_search.cpp:66: Failure
Expected equality of these values:
  route_planner.CalculateHValue(start_node)
    Which is: 0.031656995
  1.1329799
/home/sj/learning/cpp_nanodegree/CppND-Route-Planning-Project/test/utest_rp_a_star_search.cpp:67: Failure
Expected equality of these values:
  route_planner.CalculateHValue(end_node)
    Which is: 4.6308042e+27
  0.0f
    Which is: 0
/home/sj/learning/cpp_nanodegree/CppND-Route-Planning-Project/test/utest_rp_a_star_search.cpp:68: Failure
Expected equality of these values:
  route_planner.CalculateHValue(mid_node)
    Which is: 4.6308042e+27
  0.58903033
[  FAILED  ] RoutePlannerTest.TestCalculateHValue (74 ms)
[ RUN      ] RoutePlannerTest.TestAddNeighbors
/home/sj/learning/cpp_nanodegree/CppND-Route-Planning-Project/test/utest_rp_a_star_search.cpp:82: Failure
Expected equality of these values:
  neighbors.size()
    Which is: 0
  4
[  FAILED  ] RoutePlannerTest.TestAddNeighbors (70 ms)
[ RUN      ] RoutePlannerTest.TestConstructFinalPath
/home/sj/learning/cpp_nanodegree/CppND-Route-Planning-Project/test/utest_rp_a_star_search.cpp:102: Failure
Expected equality of these values:
  path.size()
    Which is: 0
  3
Segmentation fault (core dumped)
```

**Comment by zenetio** [comment]
Hey @sharathrjtr, the better way to find out what is going on is to run the project under debugger, set same breakpoints and verify variable values. Note you are getting wrong h values, wrong neighbours, wrong path size and others issues. Running under debug will facilitate fix these issues.
Cheers.

**Comment by mhalt** [comment]
A **“segmentation fault”** is when your program tries to access memory that it’s not allowed to access, or tries to . This can be caused by:

- Trying to dereference a null pointer (you’re not allowed to access the memory address 0)
- Trying to dereference some other pointer that isn’t in your memory
- A C++ vtable pointer that got corrupted and is pointing to the wrong place, which causes the program to try to execute some memory that isn’t executable

Check this blog article for more information: [How to get a core dump for a segfault on Linux](https://jvns.ca/blog/2018/04/28/debugging-a-segfault-on-linux/)

**Comment by ajithkrishnan** [comment]
Hi @sharathrjtr,

Were you able to resolve this issue? I am facing the same problem.
