### ISSUE TITLE
Target "OSM_A_star_search" links to target "Cairo::Cairo" but the target was not found. 

### ISSUE THREAD

**Issue by mFontoura** [udacity/CppND-Route-Planning-Project#19]
In Windows I tried to start the first project today but I'm still stuck on the setup of "Building and Running". I want to use a local environment so I'm not using the VM. I think I have installed all the dependencies correctly but I still have errors when trying to "cmake" this repo. I get an error on the line:
`add_executable(OSM_A_star_search src/main.cpp src/model.cpp src/render.cpp src/route_model.cpp src/route_planner.cpp)`
on the command line i get:
```
CMake Error at CMakeLists.txt:28 (add_executable):
  Target "OSM_A_star_search" links to target "Cairo::Cairo" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

Any ideas?

**Comment by cropec** [comment]
I've encountered the same problem and what helped was to add vckpg\installed\x64-windows\bin and add vckpg\installed\x64-windows\include to PATH. (probably just one of them would be enough I need to check which one).

Also I guess modyfing CMakeLists.txt to include paths above would do the trick

**Comment by WalidUe** [comment]
@mFontoura and @j-jakubowski I'm having the same problem, how did you fix it please? I tried to add the directories you mentioned to PATH but I still get this error message. **I would really appreciate your help since I've been stuck with the problem for a week now.**
![image](https://user-images.githubusercontent.com/11277981/83980314-9e5fc680-a90c-11ea-8efd-447ddaca7924.png)

**Comment by j-jakubowski** [comment]
To be honest after solving this problem I encountered some more difficulties and decided it's not worth wasting time on setting up this one-time project on windows.

I'd recommend using udacity workspace or setting up everything on regular VM or on Ubuntu for Windows (the latter being my weapon of choice - linux environment with IDE on windows, brilliant!)

**Comment by baoqger** [comment]
On windows, I met the same issue.

**Comment by WalidCHEKKOURI** [comment]
> On windows, I met the same issue.

I simply used their own Udacity Workspace instead.

**Comment by SudKul** [comment]
Hi @mFontoura and other participants, 
If setting up the environment takes you too long (and troublesome), consider creating a containerized environment, as suggested in this #25 
Otherwise, Udacity workspace is a ready-to-work solution for you.  
Thanks
