### ISSUE TITLE
Error when submitting: Student already has an open submission for this project. 

### ISSUE THREAD

**Issue by rohitdhonicsk** [udacity/CppND-Route-Planning-Project#26]
email-rohitiem2cal@gmail.com
Name-Rohit Kumar Gupta
My Project 1 Of C++ nanodegree showing error.First  it got approved suddenly it showing you got 
feedback on it.when i try to resubmit then it showing error ->Error when submitting: Student already has an open submission for this project.
Sir,my course will end in 10days .please solve this bug.otherwise i loose my course content and certificate

**Comment by soyoung823** [comment]
soyoung823@gmail.com
Same Error happening. "You are not permitted to submit multiple times" but I never submitted.

**Comment by SudKul** [comment]
Hi @rohitdhonicsk 
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks
