### ISSUE TITLE
Cant build this

### ISSUE THREAD

**Issue by paulgureghian** [udacity/CppND-Route-Planning-Project#29]
it keeps asking for io2d.

**Comment by adityakrmaurya** [comment]
[Follow instruction](https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md)
In end run `sudo make install`

**Comment by SudKul** [comment]
Hi @paulgureghian 
Though we are a little late to respond, we suggest you refer to the Knowledge hub and reach out to your assigned mentor for user-specific issues. 
Thanks
