### ISSUE TITLE
Executable fails on Big Sur

### ISSUE THREAD

**Issue by tiagoovieira** [udacity/CppND-Route-Planning-Project#35]
I try to run the project, I managed to successfully build and create the executable but I get the following error with IO2D. An assertion fails. I did all the steps, downloaded the library to `/thirdparty` folder, just as clang, build IO2D, and installed all the dependencies successfully.

```To specify a map file use the following format: 
Usage: [executable] [-f filename.osm]
Reading OpenStreetMap data from the following file: ../map.osm
Distance: 0 meters. 
display buffer and back buffer have different pixel layouts: 0(display buffer) and 8194(back buffer).
Assertion failed: (back_buffer_size.width >= 1. && back_buffer_size.height >= 1. && display_buffer_size.width >= 1. && display_buffer_size.height >= 1.), function _ScaledBackBufferRect, file /Users/path/CppND-Route-Planning-Project/thirdparty/P0267_RefImpl/P0267_RefImpl/P0267_RefImpl/coregraphics/xio2d_cg_display.cpp, line 9.
zsh: abort      ./OSM_A_star_search
```

**Comment by SudKul** [comment]
Hi @tiagoovieira 
We suggest you refer to the Knowledge hub and reach out to your assigned mentor for user-specific issues. 
Thanks

**Comment by JiashengYan** [comment]
> I try to run the project, I managed to successfully build and create the executable but I get the following error with IO2D. An assertion fails. I did all the steps, downloaded the library to `/thirdparty` folder, just as clang, build IO2D, and installed all the dependencies successfully.
> 
> ```
> Usage: [executable] [-f filename.osm]
> Reading OpenStreetMap data from the following file: ../map.osm
> Distance: 0 meters. 
> display buffer and back buffer have different pixel layouts: 0(display buffer) and 8194(back buffer).
> Assertion failed: (back_buffer_size.width >= 1. && back_buffer_size.height >= 1. && display_buffer_size.width >= 1. && display_buffer_size.height >= 1.), function _ScaledBackBufferRect, file /Users/path/CppND-Route-Planning-Project/thirdparty/P0267_RefImpl/P0267_RefImpl/P0267_RefImpl/coregraphics/xio2d_cg_display.cpp, line 9.
> zsh: abort      ./OSM_A_star_search
> ```

Hey, I'm having the same issue, did you found out a solution?
